scf/bases/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from bases.views import Home

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
]

scf/inv/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew

urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
]

scf/scf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('admin/', admin.site.urls),
]

scf/bases/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    user_crea = models.ForeignKey(User, on_delete=models.CASCADE)
    user_modifica = models.IntegerField(blank=True, null=True)

    class Meta:
        abstract=True

scf/inv/models.py
from django.db import models
from bases.models import ClaseModelo


# Create your models here.
class Categoria(ClaseModelo):
    descripcion = models.CharField(max_length=100, help_text='Descripción de la categoría', unique=True)

    def __str__(self):
        return self.descripcion

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = "Categorías"

scf/inv/forms.py
from django import forms

from .models import Categoria

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['descripcion', 'estado']
        labels = {
            'descripcion': "Descripción de la categoría",
            'estado': "Estado"
        }
        widget = {
            'descripcion': forms.TextInput
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class': 'form-control'
                })

scf/bases/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic


# Create your views here.
class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'bases/home.html'
    login_url = 'bases:login'

scf/inv/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from .models import Categoria
from .forms import CategoriaForm
from django.urls import reverse_lazy


class CategoriaView(LoginRequiredMixin, generic.ListView):
    model = Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"
    login_url = "bases:login"

class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model = Categoria
    template_name = 'inv/categoria_form.html'
    context_object_name = 'obj'
    form_class = CategoriaForm
    success_url = reverse_lazy('inv:categoria_list')
    login_url = "bases:login"

    def form_valid(self, form):
        form.instance.user_crea = self.request.user
        return super().form_valid(form)

scf/bases/templates/bases/home.html
{% extends 'base/base.html' %}

scf/bases/templates/bases/login.html
{% extends 'base/base.html' %}

{% block side-bar %} {% endblock %}
{% block top-bar %} {% endblock %}
{% block page-content %} {% endblock %}
{% block footer %} {% endblock %}

{% block login %}
    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row justify-content-center">

                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Bienvenido</h1>
                                        <small class="text-danger">
                                            {% if form.error %}
                                                {% for field in form %}
                                                    {% if field.errors %}
                                                        {% for error in field.errors %}
                                                            {{ error|escape }}
                                                        {% endfor %}
                                                    {% endif %}
                                                {% endfor %}

                                                {% if form.non_field_errors %}
                                                    {% for error in form.non_field_errors %}
                                                        {{ error|escape }}
                                                    {% endfor %}
                                                {% endif %}
                                            {% endif %}
                                        </small>
                                    </div>
                                    <form class="user" method="POST">
                                        <div class="form-group">
<!--                                            <input type="text" class="form-control form-control-user"-->
<!--                                                name="username" id="id_username" aria-describedby="emailHelp"-->
<!--                                                placeholder="Usuario...">-->
                                            <input type="text" class="form-control form-control-user" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username" placeholder="Usuario...">
                                        </div>
                                        <div class="form-group">
<!--                                            <input type="password" name="password" class="form-control form-control-user"-->
<!--                                                id="id_password" placeholder="Contraseña">-->
                                            <input type="password" class="form-control form-control-user" name="password" required="" id="id_password" placeholder="Contraseña">
                                        </div>
                                        {#{ form.as_p }#}
                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Acceder
                                        </button>
                                        {% csrf_token %}
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock %}

scf/inv/templates/inv/categoria_form.html
{% extends 'base/base.html' %}

{% block page_content %}
    <form method="POST" class="form-inline">
        {% csrf_token %}
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Nueva Categoría
                        </div>
                        <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col-10">
                                    <div class="input-group">
                                        <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción" value="">
                                    </div>
                                </div>
                                <div class="col-2">
                                    <div class="form-group">
                                        <label for="id_estado">Estado</label>
                                        <input type="checkbox" name="estado" class="form-control" id="id_estado">
                                    </div>
                                </div>
                            </div>
                        <div class="dropdown-divider"></div>
                            <div class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-danger"> <span class="fa fa-save"></span> Guardar </button>
                                    <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"> <span class="fa fa-undo"></span> Cancelar</a>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block js_page %}
{% endblock %}

scf/inv/templates/inv/categoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}

    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Listado de Categorías</h6>
            <div class="dropdown no-arrow">
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                    <div class="dropdown-header">Acciones</div>
                    <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </div>
        </div>
        <!-- Card Body -->
        <div class="card-body">
            {% if not obj %}
                <div class="alert alert-info" role="alert">
                  No hay Categorías
                </div>
            {% else %}

            <table class="table table-striped table-hover">
                <thead>
                    <th>Id</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                    <th>Fecha Creado</th>
                    <th>Fecha Modificado</th>
                    <th class="all">Acciones</th>
                </thead>
                <tbody>
                    {% for item in obj %}
                        <tr>
                            <th>{{ item.id }}</th>
                            <th>{{ item.descripcion }}</th>
                            <th>{{ item.estado }}</th>
                            <th>{{ item.fecha_creacion | date:"d/m/Y H:i:s" }}</th>
                            <th>{{ item.fecha_modificacion }}</th>
                            <th>
                                <a href="#" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                                <a href="#" class="btn btn-danger btn-circle" role="button"><i class="far fa-trash-alt"></i></a>
                            </th>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block js_page %}

{% endblock %}